[package]
name = "rsftp"
version = "0.1.0"
description = "a sftp terminal client"
authors = ["LooJee <mynameislujie1992@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"
clap = "4.5.40"
